Add pre-exec to solr-jetty charm

diff --git a/hooks/install b/hooks/install
--- a/hooks/install
+++ b/hooks/install
@@ -1,4 +1,18 @@
 #!/bin/bash
 set -eu
+
+# Pre-exec
+if [[ -d exec.d ]]; then
+    shopt -s nullglob
+    for f in exec.d/*/charm-pre-install; do
+    [[ -x "$f" ]] || continue
+    ${SHELL} -c "$f"|| {
+        ## bail out if anyone fails
+        juju-log -l ERROR "$f: returned exit_status=$? "
+        exit 1
+    }
+    done
+fi
+
 # default-jdk should be a prerequisite for jetty (Bug#1046732)
 apt-get install -y solr-jetty default-jdk curl
